// Code generated by protoc-gen-go. DO NOT EDIT.
// source: petstore.proto

package grpc2grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Timestamp1           int64    `protobuf:"varint,1,opt,name=timestamp1,proto3" json:"timestamp1,omitempty"`
	Timestamp2           int64    `protobuf:"varint,2,opt,name=timestamp2,proto3" json:"timestamp2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_petstore_933e464048d84f86, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetTimestamp1() int64 {
	if m != nil {
		return m.Timestamp1
	}
	return 0
}

func (m *User) GetTimestamp2() int64 {
	if m != nil {
		return m.Timestamp2
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "grpc2grpc.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PetStoreServiceClient is the client API for PetStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PetStoreServiceClient interface {
	BulkUsers(ctx context.Context, opts ...grpc.CallOption) (PetStoreService_BulkUsersClient, error)
}

type petStoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewPetStoreServiceClient(cc *grpc.ClientConn) PetStoreServiceClient {
	return &petStoreServiceClient{cc}
}

func (c *petStoreServiceClient) BulkUsers(ctx context.Context, opts ...grpc.CallOption) (PetStoreService_BulkUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PetStoreService_serviceDesc.Streams[0], "/grpc2grpc.PetStoreService/BulkUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &petStoreServiceBulkUsersClient{stream}
	return x, nil
}

type PetStoreService_BulkUsersClient interface {
	Send(*User) error
	Recv() (*User, error)
	grpc.ClientStream
}

type petStoreServiceBulkUsersClient struct {
	grpc.ClientStream
}

func (x *petStoreServiceBulkUsersClient) Send(m *User) error {
	return x.ClientStream.SendMsg(m)
}

func (x *petStoreServiceBulkUsersClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PetStoreServiceServer is the server API for PetStoreService service.
type PetStoreServiceServer interface {
	BulkUsers(PetStoreService_BulkUsersServer) error
}

func RegisterPetStoreServiceServer(s *grpc.Server, srv PetStoreServiceServer) {
	s.RegisterService(&_PetStoreService_serviceDesc, srv)
}

func _PetStoreService_BulkUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PetStoreServiceServer).BulkUsers(&petStoreServiceBulkUsersServer{stream})
}

type PetStoreService_BulkUsersServer interface {
	Send(*User) error
	Recv() (*User, error)
	grpc.ServerStream
}

type petStoreServiceBulkUsersServer struct {
	grpc.ServerStream
}

func (x *petStoreServiceBulkUsersServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func (x *petStoreServiceBulkUsersServer) Recv() (*User, error) {
	m := new(User)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PetStoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc2grpc.PetStoreService",
	HandlerType: (*PetStoreServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BulkUsers",
			Handler:       _PetStoreService_BulkUsers_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "petstore.proto",
}

func init() { proto.RegisterFile("petstore.proto", fileDescriptor_petstore_933e464048d84f86) }

var fileDescriptor_petstore_933e464048d84f86 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x48, 0x2d, 0x29,
	0x2e, 0xc9, 0x2f, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0x2f, 0x2a, 0x48,
	0x36, 0x02, 0x11, 0x4a, 0x6e, 0x5c, 0x2c, 0xa1, 0xc5, 0xa9, 0x45, 0x42, 0x72, 0x5c, 0x5c, 0x25,
	0x99, 0xb9, 0xa9, 0xc5, 0x25, 0x89, 0xb9, 0x05, 0x86, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41,
	0x48, 0x22, 0x28, 0xf2, 0x46, 0x12, 0x4c, 0x68, 0xf2, 0x46, 0x46, 0x2e, 0x5c, 0xfc, 0x01, 0xa9,
	0x25, 0xc1, 0x20, 0x4b, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x0c, 0xb9, 0x38, 0x9d,
	0x4a, 0x73, 0xb2, 0x41, 0xc6, 0x17, 0x0b, 0xf1, 0xeb, 0xc1, 0xed, 0xd4, 0x03, 0x89, 0x48, 0xa1,
	0x0b, 0x68, 0x30, 0x1a, 0x30, 0x26, 0xb1, 0x81, 0xdd, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xca, 0x01, 0x63, 0xd9, 0xb1, 0x00, 0x00, 0x00,
}
